"""add bills

Revision ID: e9ff20074dc3
Revises: ecd4e2bcb10f
Create Date: 2023-09-15 18:47:32.243856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9ff20074dc3'
down_revision = 'ecd4e2bcb10f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Enum('Weekly', 'Monthly', 'Annual', name='frequencyenum'), nullable=False),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('bill_id'),
    sa.UniqueConstraint('name', 'user_id', name='unq_user_bill')
    )
    op.create_table('upcoming_bill',
    sa.Column('upcoming_bill_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Enum('Weekly', 'Monthly', 'Annual', name='frequencyenum'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.bill_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('upcoming_bill_id'),
    sa.UniqueConstraint('bill_id', 'due_date', name='unq_upcoming')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcoming_bill')
    op.drop_table('bill')
    # ### end Alembic commands ###
